[workspace]
members = [
    "programs/*"
]
resolver = "2"

[patch.crates-io]
# Устраняем проблему с Edition 2024 в глубоких зависимостях
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3", tag = "1.5.1" }
wit-bindgen = { git = "https://github.com/bytecodealliance/wit-bindgen", tag = "v0.24.0" }
